import { Footer } from "@/components/footer";
import { Header } from "@/components/header/header";
import { Space_Mono } from "@next/font/google";
import Head from "next/head";
import { ReactNode } from "react";

const spaceMono = Space_Mono({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-space-mono",
  display: "swap",
});

export function Layout({ children }: { children: ReactNode }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        {process.env.NEXT_PUBLIC_IS_PRODUCTION !== "true" && <meta name="robots" content="noindex,nofollow" />}
      </Head>
      <Header />
      <main className={`bg-black ${spaceMono.variable} font-sans`}>{children}</main>
      <Footer />
    </>
  );
}
